config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new'
  get 'reset', to: 'games#reset'
  get 'score', to: 'games#score'
  post 'score', to: 'games#score'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @letters = ('A'..'Z').to_a.sample(10)
  end

  def score
    @letters = params[:array_of_letters].split()
    @word = params[:word].upcase
    url = "https://wagon-dictionary.herokuapp.com/#{@word}"
    response = RestClient.get(url)
    response_parsed = JSON.parse(response)
    if !(@word.split('') - @letters).empty?
      @answer = "Sorry but #{@word} can't be built out of #{@letters}"
    elsif response_parsed["found"]
      @answer = "Congratulations! #{@word} is a valid English word!"
      if session.key?(:score)
        session[:score] += @word.length
      else session[:score] = @word.length
      end
    else
      @answer = "Sorry but #{@word} does not seem to be a valid English word...."
    end
  end

  def reset
    session[:score] = 0
    redirect_to :controller => 'games', :action => 'new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container">
  <div class="letter-list">
    <ul>
      <% @letters.each do |letter| %>
        <li class="inline"><%= letter %></li>
      <% end %>
    </ul>
  </div>
  <form action="/score" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :array_of_letters, @letters %>
    <p>What is the longest word you can find?</p>
    <input type="text" name="word" placeholder="">
    <input type="submit">
  </form>
</div>

app/views/games/score.html.erb
<div class="container">
  <div class="letter-list">
    <ul>
      <% params[:array_of_letters].split().each do |letter| %>
        <li class="inline"><%= letter %></li>
      <% end %>
    </ul>
  </div>
  <%= @answer  %>
  <div class="score-tracker">
    <p>Score:</p>
    <%= session[:score]  %>
  </div>
  <button class="reset-btn">
    <%= link_to 'Reset score', reset_path  %>
  </button>
  <button class = "play-btn">
    <%= link_to 'Play again', new_path  %>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>